server:
  port: 8086
spring:
  elasticsearch:
    jest:
      uris: http://192.168.20.100:9200
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  rabbitmq:
    host: 192.168.20.100
    virtual-host: /xiangge
    username: xiangge
    password: xiangge

