server:
  port: 8089

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

auth:
  jwt:
    publicKeyPath: D:\\develop_code\\tmp\\rsa.pub
    privateKeyPath: D:\\develop_code\\tmp\\rsa.pri
    expire: 180 #\u5355\u4F4D\u5206\u949F
    cookieName: GMALL_TOKEN
    secret: s159ho12qhggn